repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
    - id: mypy
      args: [--ignore-missing-imports]
      additional_dependencies:
        - 'types-requests==2.25.11'
        - 'types-tabulate==0.8.3'
        - 'types-PyYAML==6.0.0'
        - 'pydantic==1.9.0'
  - repo: local
    hooks:
    - id: detect_cassette_secrets
      name: Check for secrets in VCR cassettes
      language: script
      files: "tests/cassettes/.*"
      types: [yaml]
      entry: scripts/detect_cassette_secrets.bash